name: Matrix workflow
on: push
jobs:
    build:
        continue-on-error: true
        strategy: #  strategia wykonywania
            matrix: # definicja matrixa
                node-version: [12, 14, 16] # wartość jaką chcemy zmienić
                operating-system: [ubuntu-latest, windows-latest]
                include: # jeśli chcemy prócz matrixa dać jakąś kombinacje
                    - node-version: 18
                      operating-system: ubuntu-latest # w ten sposób prócz matrixa poleci jescze job z obcją node 18 os ubuntu-latest
                exclude:
                    - node-version: 12 # w ten sposób "wycinamy" z matrixa jakąś konfigurację
                      operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }} # matrix kontekst zawiera nasze opcje zdefiniowane dla matrixa
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: build project
              run: npm run build