name: Reusable Deploy
on: 
    workflow_call: # event pozwalający na call w innym workflow
        inputs: # definicja inputów
            artifact-name: # nazwa definiowana przez nas
                description: Nazwa naszego artefacktu # opis co ma być podane
                required: false #  definujemy czy jest wymagany input
                default: dist # wartość domyśna
                type: string # definicja jaki rodzaj inputu jest oczekiwany
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }} # wyciągamy watość z kontekstu input
            - name: Output information
              run: ls